Vagrant.configure("2") do |config|
  config.vm.define "azure_devops_agent" do |azure_devops_agent|
    azure_devops_agent.vm.box = "bento/ubuntu-16.04"
    azure_devops_agent.vm.provision "ansible_local" do |ansible|
      ansible.become = true
      ansible.playbook = "playbook.yml"
    end
  end
end